### ISSUE TITLE
Collecting gitpython 超时

### ISSUE THREAD

**Issue by bnubobby** [FlowCI/plugin-gitclone#3]
HTTPSConnectionPool(host='pypi.org', port=443): Read timed out.

'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

是否可以更换国内pip源?

**Comment by gy2006** [comment]
可以通过添加 `FLOWCI_PIP_SOURCE` 变量来指定

```yaml
steps:
  - name: clone
    plugin: 'gitclone'
    envs:
      FLOWCI_PIP_SOURCE: "http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com"
```
